export const MAIN_SET_MESSAGE = 'MAIN_SET_MESSAGE'
export const MAIN_SET_FETCHING = 'MAIN_SET_FETCHING'

export const AUTHORS_SET_DATA = 'AUTHORS_SET_DATA'
export const BOOKS_SET_DATA = 'BOOKS_SET_DATA'
